### ISSUE TITLE
Failed to load the autocomplete-emojis package

### ISSUE THREAD

**Issue by WangNingning1994** [atom/autocomplete-emojis#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Microsoft Windows 7 �콢�� 
**Thrown From**: [autocomplete-emojis](https://github.com/atom/autocomplete-emojis) package, v2.2.2
### Stack Trace

Failed to load the autocomplete-emojis package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.2.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/autocomplete-emojis/lib/emojis-provider.coffee:3:14)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/autocomplete-emojis/lib/emojis-provider.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.2.3\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-emojis, v2.2.2
color-picker, v2.0.13
emmet, v2.3.14
seti-syntax, v0.4.1
seti-ui, v0.8.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by eqot** [comment]
I tried to reproduce it on OSX but could not.

I found the same or similar issues like [this](https://github.com/Peekmo/atom-autocomplete-php/issues/68) and [this](https://github.com/atom/autocomplete-snippets/issues/45).
These seem to be neither this package's issue nor fuzzaldrin's issue.

In order to identify where root cause is, could you try to run `npm install fuzzaldrin` in a terminal to check if you can download fuzzaldrin under `node_modules/fuzzaldrin`, please?

**Comment by WangNingning1994** [comment]
I tried this, I can download fuzzaldrin under node_modules/fuzzaldrin. But the problem still exists.
